#ifndef ASSEMBLY_ASMGRAPHICS_H
#define ASSEMBLY_ASMGRAPHICS_H
/*
**    $VER: asmgraphics.h 41.0 (01-Jan-1995)
**    Includes Release 41.1
**
**    Basic graphics operations.
**
**    (No) Copyrights, Public Domain Software
**            Nothing Rights Reserved
*/

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#ifndef GRAPHICS_RASTPORT_H
#include <graphics/rastport.h>
#endif

#ifndef INTUITION_INTUITION_H
#include <intuition/intuition.h>
#endif

/*
** ASTX_Justification type support for TextFmtRastPortArgs()
*/

#define ASJ_LEFT     0
#define ASJ_RIGHT    1
#define ASJ_CENTER   2

#endif /* ASSEMBLY_ASMGRAPHICS_H */
