#ifndef ASSEMBLY_ASMLIBRARIES_H
#define ASSEMBLY_ASMLIBRARIES_H
/*
**    $VER: asmlibraries.h 41.1 (20.10.94)
**    Includes Release 41.1
**
**    Special Libraries support... basic structure and define
**
**    (No) Copyrights, Public Domain Software
**            Nothing Rights Reserved
*/

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

/* =========================================================================
** === Miscellaneus ========================================================
** =========================================================================
*/

/*
** Type set in RevertMem()
*/

#define TYPEF_WORD (1<<0)
#define TYPEF_LONG (1<<1)

#endif /* ASSEMBLY_ASMLIBRARIES_H */
